### ISSUE TITLE
Issue during training with utils.deepcluster_vgg16

### ISSUE THREAD

**Issue by rohanksaxena** [subhc/unsup-parts#11]
Hello,

In the file models/feature_extraction.py line 46, you are importing vgg16 from utils.deepcluster_vgg16, but I am unable to find it anywhere. It is not under the utils directory in the root folder. I also searched the repo, but I could not find any mentions of deepcluster_vgg16. Can you please help me with this? Many thanks!

**Comment by subhc** [comment]
Thank you for your interest! Please find it attached. [deepcluster_vgg16.py.zip](https://github.com/subhc/unsup-parts/files/9367880/deepcluster_vgg16.py.zip)
