### ISSUE TITLE
Inspirational work! Question about visual consistency loss

### ISSUE THREAD

**Issue by HenryPengZou** [subhc/unsup-parts#4]
Hi, thanks for the great and very inspirational work. It helps me learn a lot from your def. of parts&object, motivation of your several different losses and ablation study! 

But I am still a little confused about the visual consistency loss(in Sec.3.2), where you mentioned that the Gaussian model was used. However, I didn't find the Gaussian model in equation(4). Where do you utilize the Gaussian model? Could you generously send me(email: pzou3@uic.edu) the code about how you implement the visual consistency loss in Sec.3.2? I really appreciate your work and help, thanks a lot!

**Comment by subhc** [comment]
I have updated the repo to include the code, thanks.

So the main intuition was that if the pixels are normally distributed around the mean, the MLE of the network parameters is equivalent to optimizing with an L2 loss. Similar to how they arrive at Eqn 5.66 in the [deeplearningbook](https://www.deeplearningbook.org/contents/ml.html).
